version: "3.8"

services:
  patient-risk-assessment:
    image: patient-risk-assessment
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - patient-demographics-api
      - abernathy-clinic-patient-record
    networks:
      - patient-services-network

  patient-demographics-api:
    image: docker-spring-boot-postgres:latest
    build: ../patient-demographics-api
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - patient-services-network

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "15432:5432"
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    networks:
      - patient-services-network

  abernathy-clinic-patient-record:
    image: abernathy-clinic-patient-record
    build: ../abernathy-clinic-patient-record
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/abernathy_clinic
    networks:
      - patient-services-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - patient-services-network

volumes:
  mongo-data:

networks:
  patient-services-network:
    name: patient-services-network